### ISSUE TITLE
Refine the written python code into PEP 8 style (only the functions in the end)

### ISSUE THREAD

**Issue by YashRaj1506** [YashRaj1506/djangocraft_cli#1]

**Comment by yanurag-dev** [comment]
Is this issue still open? I would like to work on it.

**Comment by YashRaj1506** [comment]
Agh it was earlier, but then later i planned to reformat it with the help of the black linter... I will close this for now but i have got some better issues here, i will add them here in next 5 days. Would be great if you can help me with it.
